name: My First Workflow
on:
  push:
    branches:
    - 'master'
jobs:
  echo_the_date:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_KEY:${{secrets.OPENWEATHERMAP_API}}
    steps:
    - name: echo the date
      run: echo "The current time and date is $(date)"
    - name: echo the current branch
      run: echo ${{github.ref_name}}
  
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: setu Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.2
    - name: checkout the source
      uses: actions/checkout@v3
    - name: run test
      run: mvn clean test
    - name: deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
        heroku_email: ${{secrets.EMAIL}}
        branch: ${{github.ref_name}}
